class DataCall {
  List<String> icons = [
    'assets/icons/phone.png',
    'assets/icons/laptop.png',
    'assets/icons/perfume.png',
    'assets/icons/skincare.png',
    'assets/icons/grocery.png',
    'assets/icons/house-decoration.png',
    'assets/icons/sunglasses.png',
    'assets/icons/watch.png',
    'assets/icons/shoe.png',
    'assets/icons/school-bag.png',
    'assets/icons/dresses.png',
    'assets/icons/jewelry.png',
    'assets/icons/automotive.png',
    'assets/icons/lighting.png',
  ];
  List<String> categories = [
    "smartphones",
    "laptops",
    "fragrances",
    "skincare",
    "groceries",
    "home-decoration",
    "sunglasses",
    "watches",
    "shoes",
    "bags",
    "dresses",
    "jewellery",
    "automotive",
    "lighting",
    "furniture",
    "tops",
    "motorcycle",
  ];
}
